version: '1'
services:
  nodejs-app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017/shopDEV
      DEV_REDIS_HOST: redis
      DEV_REDIS_PORT: 6379
      DEV_APP_PORT: 3000
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  mongo-data: