version: '1'
services:
  nodejs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    env_file: ./.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      DEV_REDIS_HOST: redis
      DEV_REDIS_PORT: 6379
      DEV_APP_PORT: 3000
      DEV_DB_HOST: mongo
      DEV_DB_PORT: 27017
      DEV_DB_NAME: shopDev
      DEV_RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      LOG_LEVEL: info
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # hostport:containerport
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"   # Default RabbitMQ port for messaging
      - "15672:15672" # RabbitMQ Management Console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits: 
      memlock: 
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  mongo-data:
  esdata:
    driver: local