version: '1'
services:
  nodejs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    env_file: ./.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      DEV_REDIS_HOST: ${DEV_REDIS_HOST}
      DEV_REDIS_PORT: ${DEV_REDIS_PORT}
      DEV_APP_PORT: ${DEV_APP_PORT}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DEV_DB_PORT: ${DEV_DB_PORT}
      DEV_DB_NAME: ${DEV_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  mongo-data: